#PBE resample P-value HeatMap

# Panel A data?


# Panel B  see code for Fig_2
```{r}
gbs <- read_csv("data/fig_2/hpl_GBS_data.csv")
mapping_file <- read_csv("data/fig_2/mapping_file.csv")
AccID <- read_csv("data/fig_2/AccID.csv")
allLines_mapping <- read_csv("data/fig_2/allLines_with_GID.csv")
load("data/fig_2/pcadapt_corrected.Rimage")


# All chromosomes figure

colm %>%
  ggplot(aes(x = BP/1000000, -log10(P), colour = -log10(P))) +
  scale_color_viridis(option = "plasma", direction = -1) +
  geom_point(size = 0.3) +
  theme_cowplot(9) +
  facet_wrap( ~ CHR, ncol=5)
  #geom_segment(x = 195.495, xend = 195.505, y = 110, yend = 110, colour = "red", size = 6) +
  #xlim(5379695, 5395010) +
  #ylim(0, 130)
```


```{r}
library(pglipid)
library(ggplot2)
library(cowplot)
library(Hmisc)
library(ComplexHeatmap)
```

Panel C

```
test_genes_PBE <- file.path("../Sup_files","Supplementary_File1.csv")
set_m <- test_genes_PBE[,c("gene",pops,"sum")] %>%
  dplyr::filter( sum >0) %>%
  dplyr::select(gene:AN) %>%
  tibble::column_to_rownames("gene") %>%
  as.matrix()


# n <- length(names(genes))
n <- length(testgeneID)
Result <- SuperExactTest::supertest(SET_input(set_m) ,n=n, degree = 2:4)

pvalues <- Result$P.value

# plot(Result, Layout="landscape", sort.by="size", keep=FALSE)

# Blue plot
pglipid::plot_blue(set_m, Result$P.value)
```

Panel D

```{r}
pval        <- read.csv(file.path( "../data","fig_1", "PBE_pvalues.csv"))
pglipid_cyc <- read.csv(file.path( "../data","fig_1", "pglipid_cyc.csv"))

pwy_summary <- pval  %>%
  dplyr::left_join(pglipid_cyc, by =c(geneset ="Pathway.id") )

rownames(m) <- pwy_summary$Pathway.name


m[m ==0] = 1e-5

hm <-   ComplexHeatmap::Heatmap(
  m,
  name = "p value",
  row_names_max_width = ComplexHeatmap::max_text_width(rownames(m))
)

ht <- ComplexHeatmap::draw(hm, heatmap_legend_side = "left")

row_dend <- row_dend(ht)
row_dend <- rev(row_dend)

pwy_summary$geneset[order.dendrogram(row_dend)]
rownames(m)[order.dendrogram(row_dend)]


# s1 <- m
# n_test <- nrow(s1)*ncol(s1)
# s1[m > 0] <- ""
# s1[m <  0.05] <- "*"
# s1[m < 0.05 / n_test] <- "**"

hm <-   ComplexHeatmap::Heatmap(
  m,
  name = "p value",
  cluster_rows = row_dend,
  row_dend_reorder = FALSE,
  column_order = colnames(m),
  column_names_side = "top",
  column_names_rot = 0,
  column_names_centered = TRUE,
  column_names_gp = gpar(fontsize = 10),
  row_names_max_width = ComplexHeatmap::max_text_width(rownames(m)),
  row_names_gp = gpar(fontsize = 10)
#   cell_fun = function(j, i, x, y, width, height, fill) {
#     grid.text( s1[i, j], x, y, gp = gpar(fontsize = 10, col = "white"))
#   }
)

pdf(file = "fig_S8.pdf")
print(hm)
dev.off()

```



